ARMmbed/esp8266-driver

- ESP8266/ATParser/ATParser.cpp
Fixes #3
Current flags for mbed-os let gnu-extensions into c++ code. This issue is documented here:
https://github.com/ARMmbed/mbed-os/issues/241
This removes C struct initializers, a gnu-extension.
> Removed use of C struct initializer in C++

- ESP8266Interface.cpp
- ESP8266Interface.h
**note: no api changes**
Previously an unnecessary dichotomy was introduced between the stack and interface components of the esp8266. The esp8266 provides both operations from a single object and does not benefit from this seperation.
In this situation, multiple inheritance provides a reasonable solution, as the esp8266 class satisfies multiple interfaces.
https://github.com/mbedmicro/mbed/commit/e09565474188b905cada21166118a82e66359217 resolved an ambiguity/protection issue that prevented this consolidation
> Consolidate the ESP8266Interface and ESP8266Stack

- ESP8266Interface.cpp
- ESP8266Interface.h
Dependent on https://github.com/ARMmbed/mbed-os/pull/2434
> Fixes issue https://github.com/ARMmbed/mbed-os/issues/2399 by optionally returning a SocketAddress from TCPServer::accept().
> Add support for returning peer address from socket_accept

- ESP8266/ESP8266.cpp
Fix for #8. Recent versions (at least since the last year) of Espressif firmware do not send an OK anymore after reading the stream after getting an +IPD message.
With this patch I can run mbed-client on my recently Wifi3 Click.
Need to verify that this still works on old versions of Espressif.
@sg- @gecky
> Recent versions of ESP8266 do not send OK anymore after reading the stream after IPD

- ESP8266Interface.h
This driver does not build anymore against mbed OS master.
Quick workaround is to include "mbed.h" header instead of those specific network headers.
> Include "mbed.h" instead of directly network related headers.

- ESP8266/ESP8266.cpp
- ESP8266/ESP8266.h
- ESP8266Interface.cpp
- ESP8266Interface.h
@0xc0170 Don't merge before mbed/feature_wifi branch is merged to master.
> Port esp2866 driver to new WiFiInterface API

- ESP8266Interface.cpp
- ESP8266Interface.h
In the current version of the firmware, the esp8266 handles UDP in an odd way. Rather than packet based transactions, the esp8266 handles UDP like a connection based protocol.
To return the correct address, the esp8266 just saves the last connection established by UDP. Additionally this patch added the ability of a socket to change connection addresses.
Note: This firmware is still unable to recieve connections from arbitrary hosts.
related issue #15
cc @jankii01
> Fix invalid SocketAddress returned from recvfrom

- ESP8266/ESP8266.cpp
- ESP8266/ESP8266.h
- ESP8266Interface.cpp
- ESP8266Interface.h
Here is the AT command set for the new firmware - https://www.espressif.com/sites/default/files/documentation/4a-esp8266_at_instruction_set_en.pdf
Here are the release notes - http://bbs.espressif.com/viewtopic.php?f=46&t=2451#p8029
The new firmware deprecated a few commands, so there are minor changes to AT commands for  configuring WiFi mode and sending data on a socket. 
The new firmware allows dns lookup on ESP8266 module, so I have overriden `gethostbyname` to use this functionality. 
@geky
> Driver compatible with 2.0 Espressif firmware

- ESP8266/ESP8266.cpp
- ESP8266/ESP8266.h
- ESP8266Interface.cpp
- ESP8266Interface.h
If ESP8266 firmware version is less that v2.0.0, then we print a debug message and return an error from the connect function.  The message directs users to the wiki page for updating the firmware.
> Ensures ES8266 firmware version up to date

- ESP8266/ESP8266.cpp
Reverting CIPSENDBUF to CIPSEND to fix UDP connections. Tested on both UDP and TCP. 
Issue: https://github.com/ARMmbed/esp8266-driver/issues/25
@hasnainvirk has a PR with this fixed, this issue is currently blocking testing though so adding this PR in to address that ASAP. Feel free to delete if Hasnainvirk's changes are going in soon.
https://github.com/ARMmbed/esp8266-driver/pull/24/files
> Reverting CIPSENDBUF to CIPSEND to fix UDP connections

- README.md
In windows, apparently quotes are just copied into the definition of #defines passed on the command line. The quotes were originally to help users pass in non-alphabetic characters, but if it's going to cause problems on windows they should be omitted. Users on Linux or Mac can add the quotes themselves when needed.
Note: this is not an issue when using the config system or editting the file manually.
Need to check with @MarceloSalazar that this resolves the problem he was seeing.
> readme: Remove quotes from ssid/pass defines

- ESP8266/ATParser.lib
A recursive function in the at-parser library opened up the opportunity for a stack overflow. This was fixed in the at-parser repository.
> Recursive call in vrecv was causing the main stack to overflow in the WiFi example. Main stack usage went from {4264, 4096} to {2128,4096} with this change. Tested on GCC_ARM with K64F - ESP8266.
original pr: https://github.com/ARMmbed/ATParser/pull/5
cc @kegilbert, @deepikabhavnani
> Bring in overflow fix for the at-parser

- ESP8266Interface.cpp
- ESP8266Interface.h
The implementation of DNS lookup inside the ESP8266 firmware causes stack corruption when the name is 64 characters or longer.  This change uses the mbed OS implementation of gethostbyname instead to work around this bug.
> Use host OS gethostbyname

- ESP8266/ESP8266.cpp
As ESP8266 AT Instruction Set, few commands are deprecated in Ver2.0
Below is the list of commands, updated in this PR
1. AT+CWDHCP
2. AT+CWJAP
3. AT+CIPSTA
> Updated AT commands which were deprecated

- ESP8266Interface.cpp
By wrapping these in an `#ifndef` these can be overridden from user space (e.g. mbed_app.json). For a justification, see https://stackoverflow.com/questions/45328298/mbed-socket-connection-takes-a-long-time.
@geky @sarahmarshy
> Allow overriding the ESP8266 timeouts

- ESP8266/ATParser.lib
- ESP8266/ESP8266.cpp
- ESP8266/ESP8266.h
- README.md
- TESTS/net/tcp_hello_world/main.cpp
ARM Internal REF: IOTMORF-1232
> ESP8266 driver changes to use ATCmdParser

- ESP8266/ESP8266.cpp
- ESP8266/ESP8266.h
- ESP8266Interface.cpp
- ESP8266Interface.h
This PR fixes 2 issues
1.
ap_ssid and ap_pass were uninitialized in the constructor, this caused the interface to possibly try connecting to a ssid with random garbage as a name, same with the password.
2.
Extra colon in expected AT-command response caused that bssid of current network was never got and could not be used to get the RSSI from CWLAP-command, instead an uninitialized garbage value was used.
> Parameter fixes

- ESP8266/ESP8266.cpp
When connecting, +CWJAP_CUR is not used for reporting error codes, according to documentation it should be
[Documentation](https://www.espressif.com/sites/default/files/documentation/4a-esp8266_at_instruction_set_en.pdf)
However it clashes with normal +CWJAP_CUR -response with normal expected response values, therefore the OOB for +CWJAP_CUR is removed, it was there for possible future usage.
> Remove OOB for +CWJAP_CUR:

- ESP8266/ESP8266.cpp
- ESP8266Interface.cpp
- ESP8266Interface.h
It was not possible to scan before Wifi connect was run. The HW module is
also reset only when the driver is initialized - not in each connect as
it was previously. Reconnecting also requires first running disconnect
from now on. Fixed a bug from dhcp() - mode and enable bits were mixed
with each other when given to ATParser.
> ESP8266 retrieval of AP list made possible without need to run connect()

- ESP8266/ESP8266.cpp
- ESP8266/ESP8266.h
- ESP8266Interface.cpp
- ESP8266Interface.h
Configures the Wifi chip as Station and makes it permanent by writing it also to flash.
The driver tracks its state now on rudimentary level to avoid the situations that HW has not been powered of on reset and causes the driver to be in inconsistent state.
As a minor detail took care of couple of format string warnings.
> Disable softap and make the driver to track its own state

- ESP8266/ESP8266.cpp
- ESP8266/ESP8266.h
- ESP8266Interface.cpp
- ESP8266Interface.h
- README.md
ESP8266 does not support binding a TCP client to a certain local port but its possible to achieve this in case of UDP.
README.md updated to include the Restrictions-section. Instructions how to compile and run deprecated test cases have been removed.
> Making it possible to bind UDP client to a local port

- ESP8266/ESP8266.cpp
Beforehand sending data in bursts was not possible due to corruption.
For not known reason increasing OOB data handling frequency seems to make
things better.
> Makes sending data in bursts possible

- ESP8266/ESP8266.cpp
- ESP8266Interface.cpp
The previous implementation was happy just for seeing a single digit and accepted is as the channel number. From now on the AT parser is required to read a whole line at a time.
> Fix channel numbers detected during wifi scan

- ESP8266/ESP8266.cpp
- ESP8266/ESP8266.h
- ESP8266Interface.cpp
> Cleanup AT cmd timeouts. Free corrupted packages in package handler.

- ESP8266/ESP8266.cpp
- ESP8266/ESP8266.h
- ESP8266Interface.cpp
- ESP8266Interface.h
AT instruction manual chapter 7 lists AT messages and 3 of those are used now for connection status tracking:
WIFI CONNECTED - ESP8266 station connected to an AP.
WIFI GOT IP - ESP8266 station got IP address.
WIFI DISCONNECT - ESP8266 station disconnected from an AP
https://www.espressif.com/sites/default/files/documentation/4a-esp8266_at_instruction_set_en.pdf
> Add support for attaching a status callback for esp8266 driver

- ESP8266/ESP8266.cpp
- ESP8266/ESP8266.h
- ESP8266Interface.cpp
Check for socket handle on each socket call.
Ignore errors about already closed socket from ESP8266 side and return success. Failure is reported if handle does not exist anymore.
Revealing the timeout values to higher layers is a remnant of changes I haven't included to this PR yet. Those might or might not come later.
> Check for socket handle on each socket call

- ESP8266/ESP8266.cpp
- ESP8266/ESP8266.h
After a board where the ESP8266 was connected to was reset, the ESP8266 send incoming packets from previous session to the board until reset AT command (AT+RST) was handled. Added clearing of the socket buffer after reset command.
Added clearing of packets for a socket during socket open() and close(). This ensured that when socket ID is reused, packets from previous session are not in the socket buffer.
> ESP8266 now clears socket buffer packets on reset and close

- ESP8266Interface.cpp
- mbed_lib.json
ESP can be se to be default interface for the build by setting
"esp8266.provide-default": true, in mbed_app.json
@kjbracey-arm  Any opinions, is this the correct configuration option?
> Allow ESP8266 to provide default WifiInterface

- ESP8266/ESP8266.cpp
With STM32F4 targets UARTSerial.set_flow_control() must be called with both
pins(RTS/CTS) enabled. If only one is given assertion will fail. This change is required because of STM32F4 HAL's behavior.
`[1535456719.68][CONN][RXD] mbed assertation failed: obj_s->uart != (UARTName)NC, file: ./targets/TARGET_STM/TARGET_STM32F4/serial_device.c, line 750`
> Fixes an issue with STM32F4 flow control RTS/CTS only pin config

- ESP8266/ESP8266.cpp
- ESP8266/ESP8266.h
- ESP8266Interface.cpp
Enables TCP passive mode if ESP8266's AT firmware version is 1.7.0.0 or later. What this means that instead of ESP8266 sending data spontaneously over UART the data must be requested explicitly. No changes if older firmware is in use.
Reduces OOB processing when receiving UDP packets. This is something what should have been done already under PR #79.
```
[ ] Fix
[ ] Refactor
[ ] Target update
[X] Functionality change
[ ] Breaking change
```
> Feature tcp passive mode with AT firmware v1.7.0

- ESP8266/ESP8266.cpp
Internal bookkeeping of closed sockets is left in inconsistent state if socket gets closed normally. 
Fixes issue #93 
[X] Fix
[ ] Refactor
[ ] Target update
[ ] Functionality change
[ ] Breaking change
> Fixes internal bookkeeping of closed sockets

- ESP8266/ESP8266.cpp
- ESP8266/ESP8266.h
- ESP8266Interface.cpp
- ESP8266Interface.h
Earlier internal state stayed consistent if connection drop happened by
calling disconnect(). Now spontaneous disconnect updates also the
drivers internal state.
**NOTE** This won't fix the issue that network status change gets processed only if application interacts with the driver by calling socket_recv() or socket_send(). OOB messages are processed still only when one of these functions is called.
[X] Fix
[ ] Refactor
[ ] Target update
[ ] Functionality change
[ ] Breaking change
> Makes possible to reset the modem if connection dropped

- ESP8266/ESP8266.cpp
- ESP8266/ESP8266.h
- ESP8266Interface.cpp
- ESP8266Interface.h
- mbed_lib.json
* Renames bunch of internal functions and drops superfluous ones along the way
* Organizes ESP8266Interface's socket info
* Drops unused member variable ap_sec
* Fixes layering of network status callbacks
* Cleans up the mbed_lib.json's help-sections
[] Fix
[X] Refactor
[ ] Target update
[ ] Functionality change
[ ] Breaking change
> Refactoring - organizing socket info etc

- ESP8266/ESP8266.cpp
- ESP8266/ESP8266.h
- ESP8266Interface.cpp
- ESP8266Interface.h
Check for OOBs on background. Spawns a thread for that purpose.
[X] Fix
[] Refactor
[] Target update
[] Functionality change
[] Breaking change
> Check for OOBs on background

- ESP8266/ESP8266.cpp
In passive receive mode a maximum of 2048 bytes can be received
at a time using the CIPRECVDATA command. This commit ensures that
the command cannot be called with an amount larger than this.
> Add receive length check

- ESP8266Interface.cpp
- ESP8266Interface.h
Fixes a bug where default constructor declaration is not given even
if Arduino form factor shield is used. Required moving the defaults from
the ESP8266Interface source file to the header file.
> Bugfix, TX and RX pin defaults provided if Arduino form factor

- ESP8266/ESP8266.cpp
- ESP8266/ESP8266.h
- ESP8266Interface.cpp
- ESP8266Interface.h
To avoid AT recv() timeouts receiving data is handled as OOB. 
To get the performance improvement PR ARMmbed/mbed-os#8598 needs to be also taken into use
> AT firmware >= 1.7.0 - treat data as OOB

- ESP8266/ESP8266.cpp
ESP8266 returns more values than were being parsed.
> Fix access point scan

- ESP8266/ESP8266.cpp
- ESP8266/ESP8266.h
socket_recv calls are passed all the way to the ESP8266 regardless
of data availability.
With this change the data availability variable is checked
before sending the receive AT command. The return value is also
changed so that the caller will know to wait for an event before
calling again in non-blocking mode.
> Prevent unnecessary polling in passive receive mode

- ESP8266/ESP8266.cpp
- ESP8266Interface.h
To align with the in-tree version of this driver. Once this is accepted I'll tag the commit as v1.7.1.
> Bugfix compile for targets without uart fc
